---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 5.8.0
    chart: mimir-distributed
    helm:
      values: |
        global:
          extraEnvFrom:
            - secretRef:
                name: s3-credentials
        
        ingester:
          replicas: 3
          resources:
            limits:
              memory: 12Gi
            requests:
              cpu: 3.5
              memory: 8Gi
          persistentVolume:
            size: 100Gi
        
        distributor:
          replicas: 2
          resources:
            limits:
              memory: 5.7Gi
            requests:
              cpu: 2
              memory: 4Gi
        
        compactor:
          resources:
            limits:
              memory: 2.1Gi
            requests:
              cpu: 1
              memory: 1.5Gi
          persistentVolume:
            size: 20Gi
        
        store_gateway:
          replicas: 3
          resources:
            limits:
              memory: 2.1Gi
            requests:
              cpu: 1
              memory: 1.5Gi
          persistentVolume:
            size: 10Gi
                
        alertmanager:
          enabled: false
        minio:
          enabled: false

        mimir:
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  endpoint: s3.echo.stfc.ac.uk
                  region: RegionOne
                  secret_access_key: ${S3_SECRET_ACCESS_KEY}
                  access_key_id: ${S3_ACCESS_KEY_ID}
            blocks_storage:
              s3:
                bucket_name: mimir-s3-isis-observability
            ruler_storage:
              s3:
                bucket_name: mimir-ruler-s3-isis-observability
            limits:
              max_label_names_per_series: 100
              max_global_series_per_user: 1000000
              ingestion_rate: 50000
              ingestion_burst_size: 500000
  destination:
    namespace: mimir
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: gitops/components/mimir
    repoURL: https://github.com/ISISNeutronMuon/Observability
    targetRevision: HEAD
  destination:
    namespace: mimir
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true