---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-crds
  namespace: argocd
spec:
  destination:
    namespace: nginx-gateway
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/crd
    repoURL: https://github.com/nginx/nginx-gateway-fabric.git
    targetRevision: 58ab6e23505a542823ed2c03a580ebc028c7ebe7
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-crds
  namespace: argocd
spec:
  destination:
    namespace: nginx-gateway
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/crd
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    targetRevision: 564720a533f9ff28e65bdf898c1274ace1865245
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/nginx/charts
    targetRevision: 2.0.1
    chart: nginx-gateway-fabric
    helm:
      values: |
        nginx:
          service:
            loadBalancerIP: "130.246.81.219"
  destination:
    namespace: nginx-gateway
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true