---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: vault-op
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  allowedNamespaces:
    - "*"
  kubernetes:
    role: cluster
    serviceAccount: vault-op
    audiences:
      - vault
#      - "system:konnectivity-server"