---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: grafana
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault_operator_super_admin
    serviceAccount: vault-op
    audiences:
      - vault
#      - "system:konnectivity-server"