apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
  - name: argocd
  hostnames:
  - "observability.isis.cclrc.ac.uk"
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80