apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  parentRefs:
    - name: gateway
      namespace: nginx-gateway
      sectionName: https
  hostnames:
    - "observability.isis.cclrc.ac.uk"
  rules:
    - matches:
        - path:
            type: Exact
            value: /argocd
      filters:
        - type: Redirect
          redirect:
            path:
              replaceFullPath: /argocd/
            statusCode: 301
      backendRefs:
        - name: argocd-server
          port: 80
