apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: loki-auth
  namespace: loki
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  # Things to change:
  mount: observability
  path: loki/auth
  destination:
    name: loki-auth
    overwrite: true
    create: true
