apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: observability-basic-auth
  namespace: loki
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: loki-observability
  basicAuth:
    users:
      name: "observability-basic-auth"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: observability-basic-auth
  namespace: loki
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  # Things to change:
  mount: observability
  path: loki/observability-basic-auth
  destination:
    name: observability-basic-auth
    overwrite: true
    create: true
