apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The default project, all stuff happens here
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - 'https://github.com/ISISNeutronMuon/observability'
  - 'https://grafana.github.io/helm-charts'
  - 'https://github.com/nginx/nginx-gateway-fabric'
  - 'https://github.com/kubernetes-sigs/gateway-api.git'
  destinations:
  - namespace: "*"
    server: "https://kubernetes.default.svc"
    name: in-cluster