---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.1.2
    chart: argo-cd
    helm:
      values: |
        configs:
          params:
            server.rootpath: /argocd
        cm:
          url: https://observability.isis.cclrc.ac.uk/argocd
          application.instanceLabelKey: argocd.argoproj.io/instance
        dex.config: |
          issuer: https://observability.isis.cclrc.ac.uk/argocd/api/dex
          storage:
            type: memory
          web:
            http: 0.0.0.0:5556
          frontend:
            issuer: ArgoCD
            theme: light
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true