apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway
  listeners:
  - name: argo-cd
    port: 80
    protocol: HTTP
    hostname: observability.isis.cclrc.ac.uk
    allowedRoutes:
      namespaces:
        from: All
  - name: argo-cd
    port: 443
    protocol: HTTPS
    hostname: observability.isis.cclrc.ac.uk
    allowedRoutes:
      namespaces:
        from: All
    tls:
      certificateRefs:
        - group: ""
          kind: Secret
          name: observability-isis-tls