apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: mimir
  name: vault-op
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-read
  namespace: mimir
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-account-read
subjects:
  - kind: ServiceAccount
    name: vault-op
    namespace: mimir
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-account-read-mimir
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-op
    namespace: mimir
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-account-read
  namespace: mimir
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create" ]