---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 3.4.2
      chart: k8s-monitoring
      helm:
        values: |
          cluster:
            name: observability
          
          destinations:
            - name: metrics-service
              type: prometheus
              url: https://mimir.observability.isis.rl.ac.uk/observability/api/v1/push
              auth:
                type: basic
                usernameKey: username
                passwordKey: password
              secret:
                create: false
                name: mimir-basic-auth
                namespace: monitoring

            - name: logs-service
                type: loki
                url: https://loki.observability.isis.rl.ac.uk/observability/api/v1/push
              auth:
                type: basic
                usernameKey: username
                passwordKey: password
              secret:
                create: false
                name: loki-basic-auth
                namespace: monitoring
  
              - name: traces-service
                type: otlp
                url: https://tempo.observability.isis.rl.ac.uk/observability
                auth:
                  type: basic
                  usernameKey: username
                  passwordKey: password
                secret:
                  create: false
                  name: tempo-basic-auth
                  namespace: monitoring
                metrics: {enabled: true}
                logs: {enabled: true}
                traces: {enabled: true}

          annotationAutodiscovery:
            enabled: true
            namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]

          applicationObservability:
            enabled: false
            receivers:
              otlp:
                grpc:
                  enabled: true
            metrics:
              filters:
                metric:
                  - not(IsMatch(resource.attributes["k8s.namespace.name"], "^loki|mimir|tempo|grafana|vault-op|argocd$"))
                logs:
                  - not(IsMatch(resource.attributes["k8s.namespace.name"], "^loki|mimir|tempo|grafana|vault-op|argocd$"))
                traces:
                  - not(IsMatch(resource.attributes["k8s.namespace.name"], "^loki|mimir|tempo|grafana|vault-op|argocd$"))
          
          autoInstrumentation:
            enabled: false
            beyla:
              config:
                data:
                  discovery:
                    services:
                      - k8s_namespace: loki
                      - k8s_namespace: mimir
                      - k8s_namespace: tempo
                      - k8s_namespace: grafana
                      - k8s_namespace: vault-op
                      - k8s_namespace: argocd
          
          clusterEvents:
            enabled: true
            namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]
          
          clusterMetrics:
            enabled: true
            cadvisor:
              metricsTuning:
                includeNamespaces: [loki, mimir, tempo, grafana, vault-op, argocd]
            kube-state-metrics:
              namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]

          podLogs:
            enabled: true
            namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]

          profiling:
            enabled: false
            ebpf:
              namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]
            java:
              namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]
            pprof:
              namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]

          prometheusOperatorObjects:
            enabled: true
            probes:
              namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]
            podMonitors:
              namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]
            serviceMonitors:
              namespaces: [loki, mimir, tempo, grafana, vault-op, argocd]

          alloy-metrics:
            enabled: true

          alloy-singleton:
            enabled: true

          alloy-logs:
            enabled: true

          alloy-receiver:
            enabled: false
            alloy:
              extraPorts:
                - name: otlp-grpc
                  port: 4317
                  targetPort: 4317
                  protocol: TCP

          alloy-profiles:
            enabled: false
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: gitops/components/monitoring
    repoURL: https://github.com/ISISNeutronMuon/Observability
    targetRevision: HEAD
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true