cluster:
  name: observability

destinations:
  - name: metrics-service
    type: prometheus
    url: https://mimir.observability.isis.rl.ac.uk/observability/api/v1/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: mimir-basic-auth
      namespace: monitoring

  - name: logs-service
    type: loki
    url: https://loki.observability.isis.rl.ac.uk/observability/loki/api/v1/push
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: loki-basic-auth
      namespace: monitoring

  - name: traces-service
    type: otlp
    protocol: http
    url: https://tempo.observability.isis.rl.ac.uk/observability
    auth:
      type: basic
      usernameKey: username
      passwordKey: password
    secret:
      create: false
      name: tempo-basic-auth
      namespace: monitoring
    metrics: {enabled: true}
    logs: {enabled: true}
    traces: {enabled: true}

annotationAutodiscovery:
  enabled: true
  namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]

applicationObservability:
  enabled: false
  receivers:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
  metrics:
    filters:
      metric:
        - not(IsMatch(resource.attributes["k8s.namespace.name"], "^loki|mimir|tempo|grafana|vault-op|argocd|envoy-gateway-system|s3-exporter$"))
      logs:
        - not(IsMatch(resource.attributes["k8s.namespace.name"], "^loki|mimir|tempo|grafana|vault-op|argocd|envoy-gateway-system|s3-exporter$"))
      traces:
        - not(IsMatch(resource.attributes["k8s.namespace.name"], "^loki|mimir|tempo|grafana|vault-op|argocd|envoy-gateway-system|s3-exporter$"))

autoInstrumentation:
  enabled: false
  beyla:
    config:
      data:
        discovery:
          services:
            - k8s_namespace: loki
            - k8s_namespace: mimir
            - k8s_namespace: tempo
            - k8s_namespace: grafana
            - k8s_namespace: vault-op
            - k8s_namespace: argocd
            - k8s_namespace: envoy-gateway-system
            - k8s_namespace: s3-exporter

clusterEvents:
  enabled: true
  namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]

clusterMetrics:
  enabled: true
  cadvisor:
    metricsTuning:
      includeNamespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]
  kube-state-metrics:
    namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]

podLogs:
  enabled: true
  namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]

profiling:
  enabled: false
  ebpf:
    namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]
  java:
    namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]
  pprof:
    namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]

prometheusOperatorObjects:
  enabled: true
  probes:
    namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]
  podMonitors:
    namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]
  serviceMonitors:
    namespaces: [loki, mimir, tempo, grafana, vault-op, argocd, envoy-gateway-system, s3-exporter]

alloy-metrics:
  enabled: true

alloy-singleton:
  enabled: true

alloy-logs:
  enabled: true

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP

alloy-profiles:
  enabled: false
