---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
  - repoURL: https://grafana-community.github.io/helm-charts
    chart: grafana
    targetRevision: 13.1.0
    helm:
      values: |
        replicas: 1
        plugins:
          - yesoreyeram-infinity-datasource
        grafana.ini:
          smtp:
            enabled: true
            host: ob-mgw.stfc.ac.uk:26
            skip_verify: true
            from_name: ISIS Observability
            from_address: alerts@grafana.observability.isis.rl.ac.uk
          server:
            root_url: https://grafana.observability.isis.rl.ac.uk/
          database:
            type: postgres
            host: postgres-cluster-rw.postgres-system.svc.cluster.local:5432
            name: grafana
            user: grafana
            password: "$__env{GF_DATABASE_PASSWORD}"
            ssl_mode: disable
            wal: true
        serviceMonitor:
          enabled: false # Temporarily disabled until Alloy is deployed correctly.
        sidecar:
          alerts:
            enabled: true
          dashboards:
            enabled: true
          datasources:
            enabled: true
          notifiers:
            enabled: true
        admin:
          existingSecret: grafana-creds
          userKey: username
          passwordKey: password
        envValueFrom:
          GF_DATABASE_PASSWORD:
            secretKeyRef:
              name: grafana-creds
              key: GF_DATABASE_PASSWORD
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: gitops/components/grafana
    repoURL: https://github.com/ISISNeutronMuon/Observability
    targetRevision: HEAD
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
