---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.4.4
    chart: grafana
    helm:
      values: |
        replicas: 3
        grafana.ini:
          smtp:
            enabled: true
          server:
            root_url: https://grafana.observability.isis.rl.ac.uk/
          database:
            type: postgres
            wal: true
        serviceMonitor:
          enabled: false # Temporarily disabled until Alloy is deployed correctly.
        sidecar:
          alerts:
            enabled: true
          dashboards:
            enabled: true
          datasources:
            enabled: true
          notifiers:
            enabled: true
        admin:
          existingSecret: grafana-creds
          userKey: username
          passwordKey: password
        envFromSecret: grafana-creds
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: gitops/components/grafana
    repoURL: https://github.com/ISISNeutronMuon/Observability
    targetRevision: HEAD
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true