---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.43.0
    chart: loki
    helm:
      values: |
        loki:
          compactor: 
            retention_enabled: true
            compaction_interval: 10m
            retention_delete_delay: 2h
            delete_request_store: s3
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            max_query_lookback: 720h # 28 days
            retention_period: 720h   # 28 days
          storage:
            bucketNames:
              chunks: loki-s3-isis-observability
              ruler: loki-ruler-s3-isis-observability
            s3:
              accessKeyId: ${S3_ACCESS_KEY_ID}
              secretAccessKey: ${S3_SECRET_ACCESS_KEY}
              endpoint: https://s3.echo.stfc.ac.uk
              region: RegionOne
              s3ForcePathStyle: true #Required to make our S3 compatability work
          ingester:
            chunk_encoding: snappy
          querier:
            max_concurrent: 8
            multi_tenant_queries_enabled: true
          pattern_ingester:
            enabled: true
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
            max_line_size_truncate: true
            retention_period: 1440h  # 60 days default

        deploymentMode: Distributed
        
        ingester:
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 6
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 60
          zoneAwareReplication:
             enabled: false
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
        querier:
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 6
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 60
          maxUnavailable: 2
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
        queryFrontend:
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 6
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 60
          maxUnavailable: 1
        queryScheduler:
          replicas: 2
        distributor:
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 6
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 60
          maxUnavailable: 2
        compactor:
          replicas: 1
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
        indexGateway:
          replicas: 2
          maxUnavailable: 1
          extraArgs:
            - '-config.expand-env=true'
          extraEnv:
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: S3_SECRET_ACCESS_KEY
        
        bloomPlanner:
          replicas: 0
        bloomBuilder:
          replicas: 0
        bloomGateway:
          replicas: 0
        backend:
           replicas: 0
        read:
           replicas: 0
        write:
           replicas: 0
        singleBinary:
           replicas: 0
        minio:
          enabled: false

        gateway:
          enabled: true

        monitoring:
          serviceMonitor:
            enabled: true
  
        lokiCanary:
          extraArgs:
            - -pass=$(LOKI_PASS)
            - -user=self-monitoring
          extraEnv:
            - name: LOKI_PASS
              valueFrom:
                secretKeyRef:
                  name: loki-auth
                  key: SELF_MONITORING_PASSWORD
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: gitops/components/loki
    repoURL: https://github.com/ISISNeutronMuon/Observability
    targetRevision: HEAD
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true