loki:
  compactor: 
    retention_enabled: true
    compaction_interval: 10m
    retention_delete_delay: 2h
    delete_request_store: s3
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage:
    bucketNames:
      chunks: loki-s3-isis-observability
      ruler: loki-ruler-s3-isis-observability
    s3:
      accessKeyId: ${S3_ACCESS_KEY_ID}
      secretAccessKey: ${S3_SECRET_ACCESS_KEY}
      endpoint: https://s3.echo.stfc.ac.uk
      region: RegionOne
      s3ForcePathStyle: true #Required to make our S3 compatability work
  ingester:
    chunk_encoding: snappy
  querier:
    max_concurrent: 4
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 2160h  # 3 Months default

deploymentMode: SimpleScalable

minio:
  enabled: false

backend:
  replicas: 2
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: S3_ACCESS_KEY_ID
    - name: S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: S3_SECRET_ACCESS_KEY
read:
  replicas: 2
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: S3_ACCESS_KEY_ID
    - name: S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: S3_SECRET_ACCESS_KEY
write:
  replicas: 3
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: S3_ACCESS_KEY_ID
    - name: S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: S3_SECRET_ACCESS_KEY

gateway:
  enabled: false

lokiCanary:
  extraArgs:
    - -pass=$(LOKI_PASS)
    - -user=self-monitoring
  extraEnv:
    - name: LOKI_PASS
      valueFrom:
        secretKeyRef:
          name: loki-auth
          key: SELF_MONITORING_PASSWORD