apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-creds
  namespace: grafana
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  # Things to change:
  mount: observability
  path: grafana/creds
  destination:
    name: grafana-creds
    overwrite: true
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: grafana
spec:
  vaultConnectionRef: default
  method: kubernetes
  mount: observability
  allowedNamespaces:
    - "*"
  kubernetes:
    role: cluster
    serviceAccount: vault-op
    audiences:
      - vault
      - https://kubernetes.default.svc.cluster.local