apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-creds
  namespace: vault-op
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  # Things to change:
  mount: observability
  path: grafana/creds
  destination:
    name: grafana-creds
    namespace: grafana
    create: true