apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: grafana
  name: vault-op
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-account-read
  namespace: grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: service-account-read
subjects:
  - kind: ServiceAccount
    name: vault-op
    namespace: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-account-read
  namespace: grafana
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "subjectaccessreviews" ]
    verbs: [ "create" ]