apiVersion: v1
kind: Service
metadata:
  name: s3-exporter
  namespace: s3-exporter
  labels:
    app: s3-exporter
spec:
  selector:
    app: s3-exporter
  ports:
    - name: metrics
      port: 8000
      targetPort: metrics
      protocol: TCP
